insert into public.questions (
  section,
  topic,
  difficulty,
  question,
  choices,
  correct_answer,
  explanation
)
select
  seed.section,
  seed.topic,
  seed.difficulty,
  seed.question,
  seed.choices,
  seed.correct_answer,
  seed.explanation
from jsonb_to_recordset($$
[
  {"section":"math","topic":"Algebra","difficulty":"easy","question":"If 3x + 5 = 20, what is the value of x?","choices":[{"label":"A","text":"4"},{"label":"B","text":"5"},{"label":"C","text":"6"},{"label":"D","text":"7"}],"correct_answer":"5","explanation":"Subtract 5 from both sides to get 3x = 15. Divide by 3 to get x = 5."},
  {"section":"math","topic":"Algebra","difficulty":"easy","question":"A number n is doubled and then increased by 9. The result is 31. What is n?","choices":[{"label":"A","text":"10"},{"label":"B","text":"11"},{"label":"C","text":"12"},{"label":"D","text":"13"}],"correct_answer":"11","explanation":"The equation is 2n + 9 = 31. Subtract 9 to get 2n = 22, so n = 11."},
  {"section":"math","topic":"Algebra","difficulty":"medium","question":"If 4(x - 2) = 2x + 10, what is the value of x?","choices":[{"label":"A","text":"6"},{"label":"B","text":"7"},{"label":"C","text":"8"},{"label":"D","text":"9"}],"correct_answer":"9","explanation":"Expand to get 4x - 8 = 2x + 10. Then 2x = 18, so x = 9."},
  {"section":"math","topic":"Algebra","difficulty":"medium","question":"The line y = 2x + b passes through (3, 11). What is b?","choices":[{"label":"A","text":"3"},{"label":"B","text":"4"},{"label":"C","text":"5"},{"label":"D","text":"6"}],"correct_answer":"5","explanation":"Substitute x = 3 and y = 11: 11 = 2(3) + b, so b = 5."},
  {"section":"math","topic":"Algebra","difficulty":"hard","question":"If the system x + y = 14 and 2x - y = 7 is solved, what is the value of x?","choices":[{"label":"A","text":"5"},{"label":"B","text":"6"},{"label":"C","text":"7"},{"label":"D","text":"8"}],"correct_answer":"7","explanation":"Add the equations to get 3x = 21. Therefore x = 7."},
  {"section":"math","topic":"Advanced Math","difficulty":"easy","question":"Which expression is equivalent to x^2 + 7x + 12?","choices":[{"label":"A","text":"(x + 3)(x + 4)"},{"label":"B","text":"(x + 2)(x + 6)"},{"label":"C","text":"(x - 3)(x - 4)"},{"label":"D","text":"(x + 1)(x + 12)"}],"correct_answer":"(x + 3)(x + 4)","explanation":"The factors of 12 that add to 7 are 3 and 4."},
  {"section":"math","topic":"Advanced Math","difficulty":"medium","question":"For f(x) = x^2 - 2x, what is f(5)?","choices":[{"label":"A","text":"10"},{"label":"B","text":"15"},{"label":"C","text":"20"},{"label":"D","text":"25"}],"correct_answer":"15","explanation":"f(5) = 5^2 - 2(5) = 25 - 10 = 15."},
  {"section":"math","topic":"Advanced Math","difficulty":"medium","question":"If (x + 2)^2 = 49 and x is positive, what is x?","choices":[{"label":"A","text":"5"},{"label":"B","text":"7"},{"label":"C","text":"9"},{"label":"D","text":"11"}],"correct_answer":"5","explanation":"Since x + 2 = 7 for the positive solution, x = 5."},
  {"section":"math","topic":"Advanced Math","difficulty":"hard","question":"The function g is defined by g(x) = 3x^2 + k. If g(2) = 17, what is k?","choices":[{"label":"A","text":"3"},{"label":"B","text":"5"},{"label":"C","text":"7"},{"label":"D","text":"9"}],"correct_answer":"5","explanation":"g(2) = 3(4) + k = 12 + k. Since 12 + k = 17, k = 5."},
  {"section":"math","topic":"Advanced Math","difficulty":"hard","question":"Which value of x satisfies x^2 - 6x + 8 = 0?","choices":[{"label":"A","text":"1"},{"label":"B","text":"2"},{"label":"C","text":"6"},{"label":"D","text":"8"}],"correct_answer":"2","explanation":"The quadratic factors as (x - 2)(x - 4) = 0, so x = 2 or x = 4. Among the choices, 2 works."},
  {"section":"math","topic":"Problem Solving & Data Analysis","difficulty":"easy","question":"A class has 12 juniors and 18 seniors. What percent of the class are juniors?","choices":[{"label":"A","text":"30%"},{"label":"B","text":"40%"},{"label":"C","text":"50%"},{"label":"D","text":"60%"}],"correct_answer":"40%","explanation":"There are 30 students total. The junior fraction is 12/30 = 0.40, or 40%."},
  {"section":"math","topic":"Problem Solving & Data Analysis","difficulty":"easy","question":"If 5 notebooks cost $15, what is the cost of 8 notebooks at the same rate?","choices":[{"label":"A","text":"$18"},{"label":"B","text":"$21"},{"label":"C","text":"$24"},{"label":"D","text":"$30"}],"correct_answer":"$24","explanation":"Each notebook costs $3. Eight notebooks cost 8 x 3 = $24."},
  {"section":"math","topic":"Problem Solving & Data Analysis","difficulty":"medium","question":"The mean of 6, 8, 10, and x is 9. What is x?","choices":[{"label":"A","text":"12"},{"label":"B","text":"14"},{"label":"C","text":"16"},{"label":"D","text":"18"}],"correct_answer":"12","explanation":"A mean of 9 for 4 numbers means the sum is 36. Since 6 + 8 + 10 = 24, x = 12."},
  {"section":"math","topic":"Problem Solving & Data Analysis","difficulty":"medium","question":"A store discounts a jacket from $80 to $68. What is the percent decrease?","choices":[{"label":"A","text":"10%"},{"label":"B","text":"12%"},{"label":"C","text":"15%"},{"label":"D","text":"18%"}],"correct_answer":"15%","explanation":"The decrease is $12. Since 12/80 = 0.15, the percent decrease is 15%."},
  {"section":"math","topic":"Problem Solving & Data Analysis","difficulty":"hard","question":"A survey found that 45 of 150 students ride a bus to school. Based on this rate, how many of 500 students would be expected to ride a bus?","choices":[{"label":"A","text":"120"},{"label":"B","text":"135"},{"label":"C","text":"150"},{"label":"D","text":"165"}],"correct_answer":"150","explanation":"The rate is 45/150 = 0.30. For 500 students, 0.30 x 500 = 150."},
  {"section":"math","topic":"Geometry & Trigonometry","difficulty":"easy","question":"A rectangle has length 9 and width 4. What is its area?","choices":[{"label":"A","text":"13"},{"label":"B","text":"26"},{"label":"C","text":"32"},{"label":"D","text":"36"}],"correct_answer":"36","explanation":"Area of a rectangle is length times width: 9 x 4 = 36."},
  {"section":"math","topic":"Geometry & Trigonometry","difficulty":"easy","question":"A triangle has angles measuring 40 degrees and 65 degrees. What is the third angle?","choices":[{"label":"A","text":"65 degrees"},{"label":"B","text":"70 degrees"},{"label":"C","text":"75 degrees"},{"label":"D","text":"80 degrees"}],"correct_answer":"75 degrees","explanation":"Triangle angles sum to 180 degrees. The third angle is 180 - 40 - 65 = 75 degrees."},
  {"section":"math","topic":"Geometry & Trigonometry","difficulty":"medium","question":"A circle has radius 6. In terms of pi, what is its area?","choices":[{"label":"A","text":"6pi"},{"label":"B","text":"12pi"},{"label":"C","text":"36pi"},{"label":"D","text":"72pi"}],"correct_answer":"36pi","explanation":"The area of a circle is pi r^2. With r = 6, the area is 36pi."},
  {"section":"math","topic":"Geometry & Trigonometry","difficulty":"medium","question":"In a right triangle, the legs are 5 and 12. What is the hypotenuse?","choices":[{"label":"A","text":"11"},{"label":"B","text":"12"},{"label":"C","text":"13"},{"label":"D","text":"15"}],"correct_answer":"13","explanation":"Using the Pythagorean theorem, c^2 = 5^2 + 12^2 = 169, so c = 13."},
  {"section":"math","topic":"Geometry & Trigonometry","difficulty":"hard","question":"A right triangle has an angle theta with opposite side 8 and hypotenuse 17. What is sin theta?","choices":[{"label":"A","text":"8/17"},{"label":"B","text":"15/17"},{"label":"C","text":"8/15"},{"label":"D","text":"15/8"}],"correct_answer":"8/17","explanation":"Sine is opposite over hypotenuse, so sin theta = 8/17."},
  {"section":"reading-writing","topic":"Grammar & Conventions","difficulty":"easy","question":"Which choice completes the sentence correctly? The group of students ____ meeting after school.","choices":[{"label":"A","text":"are"},{"label":"B","text":"is"},{"label":"C","text":"were"},{"label":"D","text":"have"}],"correct_answer":"is","explanation":"The subject group is singular, so the singular verb is needed."},
  {"section":"reading-writing","topic":"Grammar & Conventions","difficulty":"easy","question":"Which choice is punctuated correctly?","choices":[{"label":"A","text":"Mia brought three items: pencils, paper, and a calculator."},{"label":"B","text":"Mia brought three items pencils, paper, and a calculator."},{"label":"C","text":"Mia brought three items; pencils, paper, and a calculator."},{"label":"D","text":"Mia brought three items, pencils paper and a calculator."}],"correct_answer":"Mia brought three items: pencils, paper, and a calculator.","explanation":"A colon can introduce a list after a complete sentence."},
  {"section":"reading-writing","topic":"Grammar & Conventions","difficulty":"medium","question":"Which choice completes the sentence? Neither the coach nor the players ____ available for interviews.","choices":[{"label":"A","text":"is"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"has been"}],"correct_answer":"are","explanation":"With neither/nor, the verb agrees with the nearer subject, players, which is plural."},
  {"section":"reading-writing","topic":"Grammar & Conventions","difficulty":"hard","question":"Which sentence is clearest and most concise?","choices":[{"label":"A","text":"The committee approved the plan after reviewing the budget."},{"label":"B","text":"After having reviewed the budget, the plan was approved by the committee."},{"label":"C","text":"The plan, after review of the budget, it was approved."},{"label":"D","text":"The committee, which reviewed the budget, they approved the plan."}],"correct_answer":"The committee approved the plan after reviewing the budget.","explanation":"This choice is direct, concise, and grammatically clear."},
  {"section":"reading-writing","topic":"Transitions","difficulty":"easy","question":"Which transition best completes the sentence? The trail was steep; ____, the hikers reached the top before noon.","choices":[{"label":"A","text":"however"},{"label":"B","text":"therefore"},{"label":"C","text":"for example"},{"label":"D","text":"similarly"}],"correct_answer":"however","explanation":"The second idea contrasts with the difficulty of the trail, so however fits."},
  {"section":"reading-writing","topic":"Transitions","difficulty":"medium","question":"Which transition best completes the sentence? The data were incomplete; ____, the researchers collected a second sample.","choices":[{"label":"A","text":"as a result"},{"label":"B","text":"instead"},{"label":"C","text":"nevertheless"},{"label":"D","text":"for instance"}],"correct_answer":"as a result","explanation":"The second action is a consequence of incomplete data."},
  {"section":"reading-writing","topic":"Transitions","difficulty":"medium","question":"Which transition best completes the sentence? Several cities expanded bike lanes. ____, public interest in cycling increased.","choices":[{"label":"A","text":"Likewise"},{"label":"B","text":"In contrast"},{"label":"C","text":"Earlier"},{"label":"D","text":"Although"}],"correct_answer":"Likewise","explanation":"Likewise shows a similar trend across cities."},
  {"section":"reading-writing","topic":"Transitions","difficulty":"hard","question":"Which transition best completes the sentence? The first prototype was inexpensive; ____, it failed during repeated testing.","choices":[{"label":"A","text":"moreover"},{"label":"B","text":"however"},{"label":"C","text":"therefore"},{"label":"D","text":"for example"}],"correct_answer":"however","explanation":"The sentence contrasts low cost with poor performance, so however is best."},
  {"section":"reading-writing","topic":"Vocabulary in Context","difficulty":"easy","question":"Which word best completes the sentence? The teacher gave a ____ explanation that helped the class understand the concept.","choices":[{"label":"A","text":"clear"},{"label":"B","text":"distant"},{"label":"C","text":"fragile"},{"label":"D","text":"silent"}],"correct_answer":"clear","explanation":"A clear explanation is easy to understand, which matches the sentence."},
  {"section":"reading-writing","topic":"Vocabulary in Context","difficulty":"medium","question":"Which word best completes the sentence? The artist's style is easy to recognize because it is highly ____.","choices":[{"label":"A","text":"distinctive"},{"label":"B","text":"temporary"},{"label":"C","text":"ordinary"},{"label":"D","text":"uncertain"}],"correct_answer":"distinctive","explanation":"Distinctive means noticeably different or recognizable."},
  {"section":"reading-writing","topic":"Vocabulary in Context","difficulty":"medium","question":"Which word best completes the sentence? The mayor tried to ____ concerns by answering questions directly.","choices":[{"label":"A","text":"address"},{"label":"B","text":"ignore"},{"label":"C","text":"borrow"},{"label":"D","text":"decorate"}],"correct_answer":"address","explanation":"To address concerns means to respond to or deal with them."},
  {"section":"reading-writing","topic":"Vocabulary in Context","difficulty":"hard","question":"Which word best completes the sentence? The report was praised for its ____ analysis of the city's changing population.","choices":[{"label":"A","text":"superficial"},{"label":"B","text":"thorough"},{"label":"C","text":"accidental"},{"label":"D","text":"hesitant"}],"correct_answer":"thorough","explanation":"A thorough analysis is complete and detailed."},
  {"section":"reading-writing","topic":"Reading Comprehension","difficulty":"easy","question":"A passage explains that community gardens provide fresh food and create places for neighbors to meet. What is the main idea?","choices":[{"label":"A","text":"Community gardens can benefit neighborhoods in multiple ways."},{"label":"B","text":"Fresh food is always expensive in cities."},{"label":"C","text":"Neighbors rarely work together on shared projects."},{"label":"D","text":"Gardens should only be built in rural areas."}],"correct_answer":"Community gardens can benefit neighborhoods in multiple ways.","explanation":"The passage describes both food access and community connection as benefits."},
  {"section":"reading-writing","topic":"Reading Comprehension","difficulty":"medium","question":"A passage says a scientist repeated an experiment because the first result was surprising. What can be inferred?","choices":[{"label":"A","text":"The scientist wanted to check whether the result was reliable."},{"label":"B","text":"The scientist disliked the experiment."},{"label":"C","text":"The first result was impossible."},{"label":"D","text":"The experiment had no value."}],"correct_answer":"The scientist wanted to check whether the result was reliable.","explanation":"Repeating a surprising experiment helps confirm whether the result can be trusted."},
  {"section":"reading-writing","topic":"Reading Comprehension","difficulty":"medium","question":"A paragraph states that a new bus route reduced commute times for students. Which evidence best supports this claim?","choices":[{"label":"A","text":"Students reported arriving at school 15 minutes earlier on average."},{"label":"B","text":"The buses were painted blue and white."},{"label":"C","text":"The route map was posted online."},{"label":"D","text":"Several students enjoy listening to music on buses."}],"correct_answer":"Students reported arriving at school 15 minutes earlier on average.","explanation":"This evidence directly supports the claim about reduced commute times."},
  {"section":"reading-writing","topic":"Reading Comprehension","difficulty":"hard","question":"A passage argues that small museums preserve local history that might otherwise be overlooked. Which choice best states the author's purpose?","choices":[{"label":"A","text":"To explain the value of small museums in protecting community stories"},{"label":"B","text":"To compare ticket prices at different museums"},{"label":"C","text":"To argue that large museums should close"},{"label":"D","text":"To describe how to build a museum exhibit"}],"correct_answer":"To explain the value of small museums in protecting community stories","explanation":"The passage focuses on how small museums preserve overlooked local history."},
  {"section":"reading-writing","topic":"Text Structure","difficulty":"easy","question":"A paragraph first describes a problem and then explains how a school solved it. What is the paragraph's structure?","choices":[{"label":"A","text":"Problem and solution"},{"label":"B","text":"Chronological order"},{"label":"C","text":"Cause only"},{"label":"D","text":"Definition"}],"correct_answer":"Problem and solution","explanation":"The paragraph presents an issue and then a solution."},
  {"section":"reading-writing","topic":"Text Structure","difficulty":"medium","question":"A passage compares two note-taking methods and explains strengths of each. What structure does it use?","choices":[{"label":"A","text":"Compare and contrast"},{"label":"B","text":"Sequence"},{"label":"C","text":"Narrative"},{"label":"D","text":"Question and answer"}],"correct_answer":"Compare and contrast","explanation":"The passage discusses similarities or differences between two methods."},
  {"section":"reading-writing","topic":"Text Structure","difficulty":"medium","question":"A sentence would best introduce a paragraph about why sleep improves memory. Which choice fits best?","choices":[{"label":"A","text":"Researchers have found several ways sleep supports learning."},{"label":"B","text":"Many students own alarm clocks."},{"label":"C","text":"Some beds are larger than others."},{"label":"D","text":"The history of schools is long and complex."}],"correct_answer":"Researchers have found several ways sleep supports learning.","explanation":"This sentence introduces the topic of sleep and learning clearly."},
  {"section":"reading-writing","topic":"Text Structure","difficulty":"hard","question":"Which sentence best concludes a paragraph about libraries adding digital resources?","choices":[{"label":"A","text":"Together, these changes show how libraries are adapting to modern learners."},{"label":"B","text":"Some libraries were built more than a century ago."},{"label":"C","text":"Printed books can have colorful covers."},{"label":"D","text":"Many people walk past libraries every day."}],"correct_answer":"Together, these changes show how libraries are adapting to modern learners.","explanation":"This conclusion sums up the paragraph's main idea about adaptation."}
]
$$::jsonb) as seed(
  section text,
  topic text,
  difficulty text,
  question text,
  choices jsonb,
  correct_answer text,
  explanation text
)
on conflict (question) do update
set
  section = excluded.section,
  topic = excluded.topic,
  difficulty = excluded.difficulty,
  choices = excluded.choices,
  correct_answer = excluded.correct_answer,
  explanation = excluded.explanation;
